### ISSUE TITLE
Compile error w/ latest Swift 2 integration

### ISSUE THREAD

**Issue by zbeckman** [Moya/ReactiveMoya#4]
I raised this originally over here https://github.com/Moya/Moya/issues/210#issuecomment-139129812 before I realized it's a ReactiveMoya issue.

**Comment by ashfurrow** [comment]
It's OK! We're still tracking everything over in the main Repo for now.

**Comment by ashfurrow** [comment]
Closing this as per the discussion at https://github.com/Moya/Moya/pull/169#issuecomment-139320915
